apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-blob-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: blob-fuse-mi
  mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=10  # prevent billing charges on mounting
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
  - --log-level=LOG_WARNING
  csi:
    driver: blob.csi.azure.com
    # make sure volumeHandle is unique for every storage blob container in the cluster
    volumeHandle: "nearora-rg#kuberaysa#xgboost-10g"
    volumeAttributes:
      resourceGroup: nearora-rg
      storageAccount: kuberaysa
      containerName: xgboost-10g
      protocol: fuse
      AzureStorageAuthType: MSI
      AzureStorageIdentityClientID: "8f229821-3235-49ca-8213-989f75b93d39"