---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blob-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-blob-data
  storageClassName:  blob-fuse-mi  # set as "blob-nfs" for nfs